# Jekyll Config File.
# Alan Morgan
title: Alan Morgan
email: alanxoc3@gmail.com
description: Yet another guy's blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alanxoc3.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-144820267-1

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - deploy
  - docs/
