#!/bin/bash
echo "-> Building..."
rm -r _site/
gemx bundle exec jekyll b -q

echo "-> Copy build to docs folder..."
rm -rf docs/
mv _site/ docs/

echo "-> Committing the change..."
git add -f docs # Force add, because that directory is gitignored.
git commit -m "Website update on $(date -u --rfc-3339=seconds)." > /dev/null

echo "-> Done!"
