#!/bin/bash
echo
echo "Building..."
rm -r _site/
gemx bundle exec jekyll b

echo
echo "Copy build to docs folder..."
rm -r docs/
cp _site/ docs/

echo
echo "Committing the change..."
git add docs
git commit -m "Website update on $(date -u --rfc-3339=seconds)"

echo
echo "Done!"
